// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6PZ3RbcrhFSOr1-wPHYbOjnvvFzIVZE',
    appId: '1:705774753844:android:37a6641f37c460c95bd261',
    messagingSenderId: '705774753844',
    projectId: 'mio-amore-incevio',
    storageBucket: 'mio-amore-incevio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nqsPtVlSL1mZWnceTV4ZPLiBKcG7vDc',
    appId: '1:705774753844:ios:df16d1a5cc1448395bd261',
    messagingSenderId: '705774753844',
    projectId: 'mio-amore-incevio',
    storageBucket: 'mio-amore-incevio.appspot.com',
    androidClientId: '705774753844-e6j67j4dh7msmr8fncdgs2f6un8eku4e.apps.googleusercontent.com',
    iosClientId: '705774753844-imnlfb746eondqb3vo2ttvm46toatqpu.apps.googleusercontent.com',
    iosBundleId: 'com.incevio.mioamore',
  );
}
